### ISSUE TITLE
Android TODO

### ISSUE THREAD

**Issue by SamRodri** [SamRodri/zng#410]
0.11.1 was released as Android already mostly works and it fixes the gradient panic bug, but there are more things to test:

- [x] Test orientation change.
- [x] Test text input (keyboard does not show).
- [x] Add Android to template.
- [x] Document requirements to build for Android (rust flags, activity feature, apk manifest attributes).
- [x]  Notch padding.
- [x] Default accent color does not look right
- [x] Android widget sizes (increase font?)
